### ISSUE TITLE
Ivelkov Ajavahetaja#9486 | Among ass emote

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [Zach-2000/ThatBot-Issues#26]
**Describe the Feature:** You should make that bot react to the emote like how it reacts when someone does ^say owo, or maybe make the bot reply with something like "no" or "gay" since the emote is kinda cringe and overused

**Comment by Zach-2000** [comment]
Emote must be from That Place for the bot the React to it.

**Comment by FireGen-Loading** [comment]
inaccurate discord.py can use integrated discord emotes aswell

**Comment by Zach-2000** [comment]
Yes, it can but I was referring to what limits I am setting for how this works rather than technical limits.
