### ISSUE TITLE
pinhead#4946 | [Suggestion] New React to Message Idea

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [Zach-2000/ThatBot-Issues#28]
**Describe the Feature:** When someone says water, ice juice, or ocean sauce, react with :cup_with_straw:

**Comment by pinhead-tf2** [comment]
Since that's actually an emote on GitHub, the non-emote name is cup with straw.

**Comment by Zach-2000** [comment]
Accepted - Feature will be implemented into the next update.

**Comment by Zach-2000** [comment]
[Update] Complete - Ready for 1.2.6.
