### ISSUE TITLE
MARIOWNED#250238u5908347957834 | the bot doesnt work shit

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [Zach-2000/ThatBot-Issues#29]
**Describe the Bug:** THE BOT SUCKS AND YOU WONT EVEN ANSWER MY DMS YOU BLOCKED ME YOU LITERALL GARBAGE MACHINE CCOEM O N
**Describe how to Reproduce:** DO YOU JOB AND FIX THE ISSUE WHERE I CANT DM THE FUCKING BLODEH BOT
**Describe the Expected Behavior:** FIX
THE
BOT
YOU
DUMBASS

(Optional) **Add any Additional Info:** FUCK OFF

**Comment by Zach-2000** [comment]
Invalid - Thank you for your comment.
