### ISSUE TITLE
Nikowo#7370 | me lon emoji

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [Zach-2000/ThatBot-Issues#32]
**Describe the Feature:** Please make it so the bot responds with a watermelon 🍉 emoji whenever you type "me lon" instead of only when you type "melon"

**Comment by pinhead-tf2** [comment]
i second this

**Comment by Zach-2000** [comment]
Accepted - Will be added in 1.2.6.

**Comment by Zach-2000** [comment]
[Update] Complete - Ready for 1.2.6.
