### ISSUE TITLE
weed#2053 | weed gives a plant reaction

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [Zach-2000/ThatBot-Issues#33]
**Describe the Feature:** every time somebody says weed you get a plant reaction for it

**Comment by pinhead-tf2** [comment]
this but with the custom version of weed

**Comment by Zach-2000** [comment]
Invalid - Please create a new submission with your actual discord username.

**Comment by Zach-2000** [comment]
[Re-Opened] Staff Review - Suggestion will be evaluated by staff.

**Comment by Zach-2000** [comment]
[Update] Accepted - Will be added in 1.2.6.

**Comment by Zach-2000** [comment]
[Update] Complete - Ready for 1.2.6.
