### ISSUE TITLE
I outpizzad the hut#3008 | waffle emoji reaction

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [Zach-2000/ThatBot-Issues#34]
**Describe the Feature:** whenever someone types :waffle: the bot reacts with the waffle emoji, as it does with the pancakes emoji

**Comment by Zach-2000** [comment]
Accepted - Will be added in 1.2.6.

**Comment by Zach-2000** [comment]
[Update] Complete - Ready for 1.2.6.
