### ISSUE TITLE
Rifter#0160 | funny plane

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [Zach-2000/ThatBot-Issues#36]
**Describe the Feature:** "funny plane"
That bot reacts :latos:

**Comment by Zach-2000** [comment]
Community Review - Suggestion will be evaluated via a server poll.

**Comment by Zach-2000** [comment]
[Update] Accepted - Will be added in 1.2.6.

**Comment by Zach-2000** [comment]
[Update] Complete - Ready for 1.2.6.
