### ISSUE TITLE
pinhead#4946 | Enchantment Table Translator

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [Zach-2000/ThatBot-Issues#42]
**Describe the Feature:** If someone starts to speak enchantment table, make That Bot reply to their message with a translation of what they said. For example:

pinhead: ᒷリ⊣╎リᒷᒷ∷ ⊣ᔑᒲ╎リ⊣

That Bot: pinhead said engineer gaming

**Comment by Zach-2000** [comment]
Denied - This issue may be re-evaluated in the future based on the longevity of the meme.
