### ISSUE TITLE
Rifter#0160 | 2.25 mil Yike Tokens = Unzenta furry

### ISSUE THREAD

**Issue by GoogleFormsSubmission** [Zach-2000/ThatBot-Issues#49]
**Describe the Feature:** Add a new item to the Yike Tokens Shop for 2.25 million Yike Tokens.
Basically same thing as the suka item
Image: https://cdn.discordapp.com/attachments/578357424465903686/830485784737349712/image0.png

**Comment by Zach-2000** [comment]
Invalid - This suggestion is not regarding That Bot, use the instructions in the pinned messages of #server-polls to make this suggestion instead.
