### ISSUE TITLE
A That Bot reaction request. 

### ISSUE THREAD

**Issue by Mozonite** [Zach-2000/ThatBot-Issues#5]
**Describe the Feature**
On the behalf of this user, I shall suggest for this reaction to be implemented. 
![image](https://user-images.githubusercontent.com/75358216/100844017-19271b80-3430-11eb-98f7-046fbca05c92.png)

**Did you read the guidelines?** 
yes 😳

**Comment by Zach-2000** [comment]
Suggestion accepted. Implementing into v1.2.4 ASAP. Will update when complete.
